### ISSUE TITLE
Will not log in with all the correct information

### ISSUE THREAD

**Issue by 6R1M4C3** [datawhores/OF-Scraper#117] opened 2023-07-07 11:10 UTC
this no longer will log in at all it just doesn't accept any of the information provided to it, either via the cookie helper, or the manual or even the extraction. it has just stopped working today.

**Comment by 6R1M4C3** [comment] 2023-07-07 13:17
> ofscraper_windows_cdadbad.exe si acepta introducir manualmente los datos Nomas que todas las versiones NO conectan con cdrm-project.com para obtener la key de los videos/audios drm y solo se bajan los 2 archivos encriptados o en archivos .part

I have it installed via pip not via any exe, also manually entering all the correct auth information or entering it via the cookie helper or entering it via the extraction method all result in it counting to 5 attempts to log in, the is unusual as it was only 2 days or so ago that it was working fine now it will not allow an account to log in at all.

**Comment by subjectnorica** [comment] 2023-07-08 20:46
It's the same for me as well. I've tried resetting the auth info but it's all correct and none of the info has changed. I also tried updating with pip to make sure it was the latest version and still no fix

**Comment by Boomeroo** [comment] 2023-07-09 10:59
Same here.. Would be amazing if we could fix that

**Comment by datawhores** [comment] 2023-07-09 12:24
Have you updated to a newer commit

**Comment by subjectnorica** [comment] 2023-07-09 12:39
There's a lot of new documentation now, I didn't realize that using the regular pip update didn't work, but uninstalling and reinstalling made it update fully and now it works for me. Hopefully it will for others too

**Comment by zc0n** [comment] 2023-07-09 12:57
Using the standalone exe and a brand new config and auth file I also cannot login. Nothing seems to stick out in the debug log

**Comment by jpwarak** [comment] 2023-07-09 13:04
> There's a lot of new documentation now, I didn't realize that using the regular pip update didn't work, but uninstalling and reinstalling made it update fully and now it works for me. Hopefully it will for others too

uninstalled/reinstalled using pip, and it's working fine now. Thanks!

**Comment by thisisme79** [comment] 2023-07-27 04:30
This is happening to me now, the Uninstall/Reinstall from above didn't change anything.  
pip install with forced python 3.10.11 environment.
Trying to update auth.json with either manual or clone from Edge doesn't help
Cloneing Edge allows Edge to keep working, but as soon as I try an login with ofscraper Edge OF logs me out. 
I think they are detecting it somehow and invalidating the cookie.

**Comment by datawhores** [comment] 2023-07-27 10:17
Does trying chrome or firefox work

**Comment by datawhores** [comment] 2023-07-27 23:31
nvm I think there was a bug here

Unfortuntely it only would effect a new user 
With that said I implemented a fix

**Comment by thisisme79** [comment] 2023-07-29 18:53
> Does trying chrome or firefox work

I was finally able to get it to work, I had to login under Firefox, manually import the auth.json file with F12 (Auto import left the last section and user agent incorrect) and then if finally started working...  Not sure what it was I think the user agent was what was throwing it off...

**Comment by datawhores** [comment] 2023-07-29 20:19
I made some changes that might have fix it

**Comment by ensozero** [comment] 2023-08-03 04:21
I'm getting a login error. I've verified that everything is correct.

Trying to login attempt:1/10
 [scraper.check_auth:297]  Auth Failed

I uninstalled and reinstalled with pop and the problem is the same

**Comment by pipx-install** [comment] 2023-08-03 05:50
> I'm getting a login error. I've verified that everything is correct.
> 
> Trying to login attempt:1/10 [scraper.check_auth:297] Auth Failed
> 
> I uninstalled and reinstalled with pop and the problem is the same

I'm having your same issue. I have also noticed that whenever I run the Auth, Onlyfans will log me out.

**Comment by Puk0** [comment] 2023-08-03 11:02
> I'm getting a login error. I've verified that everything is correct.
> 
> Trying to login attempt:1/10 [scraper.check_auth:297] Auth Failed
> 
> I uninstalled and reinstalled with pop and the problem is the same

> I'm having your same issue. I have also noticed that whenever I run the Auth, Onlyfans will log me out.

- Sal de tu cuenta de onlyf... 
- entra de nuevo para generar una nueva cookie 
- cierra el programa y vuelve a poner los datos 
- o edita el auth.json
- o dentro del programa usa "Only Fans-Cookie-Helper" y pega los datos
- o usa la versión 2.7.11

**Comment by ensozero** [comment] 2023-08-03 19:10
It looks like OF is logging out the account when the script attempts to authorize, so this is all happening on the OnlyFans end

**Comment by datawhores** [comment] 2023-08-07 01:41
I have a fix for this that seems to work
The down side is that it requires using a multiline input, which means a alternative to enter has to be used

You can see the available keys in the 3.0

**Comment by datawhores** [comment] 2023-08-08 18:10
Editing the auth.json file manually can also be way to solve this
This way you can confirm that the formating is correct

**Comment by datawhores** [comment] 2023-11-16 22:15
This issue is very old

If you are still having the same issue on newer version make a new issue
thank you

**Closed by datawhores** 2023-11-16 22:15 UTC
