### ISSUE TITLE
Nothing is downloading

### ISSUE THREAD

**Issue by kis1yi** [datawhores/OF-Scraper#3] opened 2023-04-03 13:36 UTC
There is a new account with one paid and free subscription to models anisyia and emakarterfree. Python 3.10.9

When trying to download content, always Progress: (0 photos, 0 videos, 0 skipped || 0): 0it [00:00, ?it/s]

Below is an example of trying to download something from an emakarterfree account.

```
C:\Users\Admin>ofscraper
Status - UP
? What would you like to do? Download content from a user
? Modify filters for accounts list?
Example scraping free accounts only Yes
? Filter account by renewal of subscription status Both
? Filter accounts based on access to content via a subscription Both
? Filter accounts by the type of subscription Both
? Would you like to also download paid content Yes
Using profile: main_profile
Status - UP
Welcome, <here_is_my_userid>
 + Getting your subscriptions (this may take awhile)...
? Which models do you want to scrape: emakarterfree
Getting Selected post type(s) for emakarterfree
Subscription Active: True
? Which area(s) would you like to scrape? (Press ENTER to continue) ['Timeline', 'Archived', 'Highlights', 'Stories', '
Messages']
 + Getting pinned media...
 + Getting timeline media...
 + Getting archived media...
 + Getting messages...
 + Getting highlights and stories...
Skipping previously downloaded
Posts left for download 0
Downloading to C:\Users\Admin\Downloads\ofscraper-main\emakarterfree
Progress: (0 photos, 0 videos, 0 skipped || 0): 0it [00:00, ?it/s]
Using profile: main_profile
Status - UP
Getting paid content for emakarterfree
Scraping, Scraping isn't frozen. It takes time.
Scraped Page:1

Username: emakarterfree
- paid content 0
 -- photos 0
 -- videos 0
 -- audios 0

Done With Run
? Do you want to continue with script No
```

**Comment by excludedBittern8** [comment] 2023-04-03 15:16
What version are you running with?

You can find out with ofscraper -v

**Comment by kis1yi** [comment] 2023-04-03 18:11
> What version are you running with?
> 
> You can find out with ofscraper -v

ofscraper 1.51
 installed today with `pip install git+https://github.com/excludedBittern8/ofscraper`

**Comment by excludedBittern8** [comment] 2023-04-03 19:27
Does running 
ofscraper --dupe
Work by chance?

**Comment by deadcode0815** [comment] 2023-04-03 19:29
ofscraper --dupe seems to do the trick (had the same issue dowloading 0 files)

**Comment by outsdr01** [comment] 2023-04-03 21:41
> ofscraper --dupe seems to do the trick (had the same issue dowloading 0 files). //EDIT: at least it starts to download media.

That also works for me. It's interesting though, because this is my first time downloading with it, so there's to duplicate.

**Comment by ctrlcmdshft** [comment] 2023-04-03 21:49
> Does running
> ofscraper --dupe
> Work by chance?

Can also confirm this works.

**Comment by outsdr01** [comment] 2023-04-03 22:05
Also, while the first model downloaded into its own folder in the ofscraper-main folder, the rest are going into %username%\AppData\Roaming\Python\Python310\site-packages\.tempmedia

**Comment by excludedBittern8** [comment] 2023-04-03 22:40
Are they not moving to the model folder?

Once a download is at 100 percent, and passes the size check. It should move to the model folder.

**Comment by deadcode0815** [comment] 2023-04-04 01:49
I was never able to download with ofscraper - only "ofscraper --dupe" did the trick for me.

**Comment by excludedBittern8** [comment] 2023-04-04 02:42
I'll look into finding what the cause of the issue is

**Comment by outsdr01** [comment] 2023-04-04 11:49
> 

Not when moving onto the next model at least. I don't know about when the entire run is finished. I'll try just doing a few at a time, instead of all of my subs at once.

**Comment by excludedBittern8** [comment] 2023-04-04 16:14
I was able to find the source of the zero downloads issue

I will hopefully be pushing  a fix for this today or tomorrow as part of the next update

**Comment by excludedBittern8** [comment] 2023-04-06 14:40
This issue should be fixed in the lastest version
I've changed how the dupe check work so they will have to be readded to the database

**Closed as completed** 2023-04-06 14:40 UTC
