### ISSUE TITLE
Video output name None.mp4 and are overwritten

### ISSUE THREAD

**Issue by naaitsab** [datawhores/OF-Scraper#78] opened 2023-06-16 10:45 UTC
When downloading and "unprotect" the newer "protected" video's the output is 'None.mp4'. This results in all of these type of video's getting overwritten and only the last one being kept. "regular" video's download just fine including their name.

Running version 2.4.2 and Python 3.10

(specifically not using specific terms to not flag the post)

**Comment by datawhores** [comment] 2023-06-16 14:29
Are you using filename for your config I have to push a fix for that
It returning none for those types of posts

**Comment by datawhores** [comment] 2023-06-16 19:58
If I'm right about the cause then it should be fixed in 2.4.3

**Comment by naaitsab** [comment] 2023-06-17 06:45
Thanks. Tried to run it again but the sub on the specific channel ended yesterday it seems 😅 so can't check it directly on that. If anyone else can confirm the fix working that would be great.

**Closed** 2023-07-27 10:18 UTC
