### ISSUE TITLE
unsupported operand type(s) for -: 'NoneType' and 'int'

### ISSUE THREAD

**Issue by sixinchfootlong** [datawhores/OF-Scraper#194] opened 2023-09-04 05:19 UTC
```
TRACEBACK  [logger.inner:187]  Traceback (most recent call last):                                                                                                                                                            logger.py:187
            File "x/OF-Scraper/ofscraper/utils/download.py", line 575, in inner
              size_checker(temp,ele,total)
            File "x/OF-Scraper/ofscraper/utils/download.py", line 229, in size_checker
              elif total-pathlib.Path(path).absolute().stat().st_size>500:
                   ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
```
Relevant code: https://github.com/datawhores/OF-Scraper/blob/b7adb8334e2eb4b684acd80c656b556623a930e3/ofscraper/utils/download.py#L536-L575

The code appears to consider `total == None` to be a valid case on line 536 but this results in the `size_checker` call on line 575 failing.

**Comment by datawhores** [comment] 2023-09-05 02:43
I think I found the cause and pushed a fix

**Closed by datawhores** 2023-09-05 02:43 UTC
